- hosts: all
  tasks:
    - name: install packages
      yum:
        name: "{{ package }}"
        state: present
      vars: 
        package: 
        - httpd
        - vim
        - tree
        - unzip  