- name: Download wordpress
  get_url:
    url: "{{ wordpress }}"
    dest: "{{ wp_des }}"

- name: extract wordpress
  unarchive:
    src: "{{ wp_des }}"
    dest: /tmp
    remote_src: yes

- name: Copy file with owner and permissions
  copy:
    src: /tmp/wordpress/.
    dest: /var/www/html
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: '755'
    remote_src: yes

- name: template 
  template:
    src: wp-config.php.j2
    dest: /var/www/html/wp-config.php
  
- name: Start and enable Apache
  service:
    name: httpd
    state: restarted